apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    app: demo-voting-app
spec:
  # type: ClusterIP is default one so we don't have to provide it
  ports:
   - port: 6379
     targetPort: 6379
  selector:
    name: redis-pod
    app: demo-voting-app