apiVersion: v1
kind: Service
metadata:
  name: db # as the worker-app expects it
  labels:
    name: postgres-service
    app: demo-voting-app
spec:
  # type: ClusterIP is default one so we don't have to provide it
  ports:
   - port: 5432
     targetPort: 5432
  selector:
    name: postgres-pod
    app: demo-voting-app